import type { Language } from './session';
export const localeNames = {"en": "English", "hi": "हिन्दी", "kn": "ಕನ್ನಡ", "ta": "தமிழ்", "te": "తెలుగు", "ml": "മലയാളം", "mr": "मराठी", "gu": "ગુજરાતી", "pa": "ਪੰਜਾਬੀ", "bn": "বাংলা", "fr": "Français", "ar": "العربية", "it": "Italiano", "ko": "한국어", "ja": "日本語"};
export type Locale = keyof typeof localeNames;
// The QR card's heading, read by the visitor in their own language.
export const scanPrompt: Record<Locale, string> = {
  en: 'Scan my conversation code',
  ar: 'امسح رمز المحادثة الخاص بي',
  it: 'Scansiona il mio codice di conversazione',
  ko: '내 대화 코드를 스캔하세요',
  ja: '私の会話コードをスキャンしてください',
  hi: 'मेरा बातचीत कोड स्कैन करें',
  kn: 'ನನ್ನ ಸಂಭಾಷಣೆ ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
  fr: 'Scannez mon code de conversation',
  gu: 'મારો વાતચીત કોડ સ્કેન કરો',
  bn: 'আমার কথোপকথন কোড স্ক্যান করুন',
  ta: 'என் உரையாடல் குறியீட்டை ஸ்கேன் செய்யுங்கள்',
  te: 'నా సంభాషణ కోడ్‌ను స్కాన్ చేయండి',
  ml: 'എന്റെ സംഭാഷണ കോഡ് സ്കാൻ ചെയ്യൂ',
  mr: 'माझा संभाषण कोड स्कॅन करा',
  pa: 'ਮੇਰਾ ਗੱਲਬਾਤ ਕੋਡ ਸਕੈਨ ਕਰੋ',
};
export const localeLanguage: Record<Locale, Language> = {"en": "English", "hi": "Hindi", "bn": "Bengali", "ta": "Tamil", "te": "Telugu", "gu": "Gujarati", "kn": "Kannada", "ml": "Malayalam", "mr": "Marathi", "pa": "Punjabi", "fr": "French", "ar": "Arabic", "it": "Italian", "ko": "Korean", "ja": "Japanese"};
export function validLocale(value: string | null): Locale { return value && Object.hasOwn(localeNames, value) ? value as Locale : 'en'; }
const en = {
  heading: 'Talk to anyone in {their>your}|native language', mobile: 'Mobile number', country: 'Country / region', name: 'Your name', firstName: 'Your first name', languages: 'Your language', select: 'Choose one language.', code: 'Verification code', test: 'Test mode: no SMS was sent.', testCode: 'Test code:', privacy: 'We will never share your phone number with the person you’re talking to.', send: 'Send verification code', verify: 'Verify & continue', finish: 'Let’s get talking', error: 'Something went wrong. Please try again.', indian: 'Enter a 10-digit Indian mobile number.', phoneError: 'Check your country code and mobile number.', choose: 'Choose a language to continue.', invalidCode: 'Incorrect or expired code. Please try again.', photo: 'Two people talking outdoors while wearing earbuds', signIn: 'Sign in and get started', loading: 'Loading Ekam…',
};
export const onboardingCopy: Record<Locale, typeof en> = {
  en,
  ja: {"heading": "誰とでも{相手の>自分の}|母国語で話しましょう", "mobile": "携帯電話番号", "country": "国 / 地域", "name": "名前", "firstName": "名", "languages": "言語", "select": "言語を選択してください。", "code": "認証コード", "test": "テストモード：SMSは送信されません。", "testCode": "テストコード：", "privacy": "電話番号が相手に公開されることはありません。", "send": "認証コードを送信", "verify": "認証して次へ", "finish": "会話を始めましょう", "error": "エラーが発生しました。もう一度お試しください。", "indian": "10桁のインドの携帯電話番号を入力してください。", "phoneError": "国番号と電話番号を確認してください。", "choose": "言語を選択して進んでください。", "invalidCode": "コードが正しくないか、期限切れです。もう一度お試しください。", "photo": "イヤホンをして屋外で会話する二人", "signIn": "サインインして始める", "loading": "Ekamを読み込み中…"},
  ko: {"heading": "누구와도 {상대방의>내}|모국어로 대화하세요", "mobile": "휴대폰 번호", "country": "국가 / 지역", "name": "이름", "firstName": "이름", "languages": "사용 언어", "select": "언어를 선택하세요.", "code": "인증 코드", "test": "테스트 모드: SMS가 발송되지 않았습니다.", "testCode": "테스트 코드:", "privacy": "귀하의 휴대폰 번호는 상대방에게 절대 공개되지 않습니다.", "send": "인증 코드 전송", "verify": "인증 및 계속하기", "finish": "대화를 시작하세요", "error": "오류가 발생했습니다. 다시 시도해 주세요.", "indian": "10자리 인도 휴대폰 번호를 입력하세요.", "phoneError": "국가 코드와 휴대폰 번호를 확인하세요.", "choose": "계속하려면 언어를 선택하세요.", "invalidCode": "코드가 잘못되었거나 만료되었습니다. 다시 시도해 주세요.", "photo": "이어버드를 착용하고 야외에서 대화하는 두 사람", "signIn": "로그인하고 시작하기", "loading": "Ekam 로딩 중..."},
  it: {"heading": "Parla con chiunque nella {sua>tua}|lingua madre", "mobile": "Numero di cellulare", "country": "Paese / regione", "name": "Il tuo nome", "firstName": "Il tuo nome", "languages": "La tua lingua", "select": "Scegli una lingua.", "code": "Codice di verifica", "test": "Modalità test: nessun SMS inviato.", "testCode": "Codice di test:", "privacy": "Non condivideremo mai il tuo numero di telefono con la persona con cui parli.", "send": "Invia codice di verifica", "verify": "Verifica e continua", "finish": "Iniziamo a parlare", "error": "Qualcosa è andato storto. Riprova.", "indian": "Inserisci un numero di cellulare indiano a 10 cifre.", "phoneError": "Controlla il prefisso internazionale e il numero di cellulare.", "choose": "Scegli una lingua per continuare.", "invalidCode": "Codice errato o scaduto. Riprova.", "photo": "Due persone che parlano all'aperto indossando auricolari", "signIn": "Accedi e inizia", "loading": "Caricamento di Ekam..."},
  ar: {"heading": "تحدّث مع أي شخص {بلغته>بلغتك}|الأم", "mobile": "رقم الهاتف المحمول", "country": "الدولة / المنطقة", "name": "اسمك", "firstName": "اسمك الأول", "languages": "لغتك", "select": "اختر لغة واحدة.", "code": "رمز التحقق", "test": "وضع الاختبار: لم يتم إرسال أي SMS.", "testCode": "رمز الاختبار:", "privacy": "لن نشارك رقم هاتفك أبداً مع الشخص الذي تتحدث معه.", "send": "إرسال رمز التحقق", "verify": "تحقق وتابع", "finish": "لنبدأ المحادثة", "error": "حدث خطأ ما. يرجى المحاولة مجدداً.", "indian": "أدخل رقم هاتف محمول هندياً مكوناً من 10 أرقام.", "phoneError": "يرجى التحقق من رمز الدولة ورقم الهاتف.", "choose": "اختر لغة للمتابعة.", "invalidCode": "الرمز غير صحيح أو منتهي الصلاحية. يرجى المحاولة مجدداً.", "photo": "شخصان يتحدثان في الخارج وهما يرتديان سماعات الأذن", "signIn": "سجل الدخول للبدء", "loading": "جاري تحميل Ekam..."},
  fr: {
    heading: 'Parlez à n’importe qui dans {sa>votre}|langue maternelle', mobile: 'Numéro de mobile', country: 'Pays / région', name: 'Votre nom', firstName: 'Votre prénom', languages: 'Votre langue', select: 'Choisissez une seule langue.', code: 'Code de vérification', test: 'Mode test : aucun SMS envoyé.', testCode: 'Code de test :', privacy: 'Votre numéro de téléphone ne sera jamais partagé avec votre interlocuteur.', send: 'Envoyer le code de vérification', verify: 'Vérifier et continuer', finish: 'Commençons à parler', error: 'Une erreur est survenue. Veuillez réessayer.', indian: 'Saisissez un numéro de mobile indien à 10 chiffres.', phoneError: 'Vérifiez votre indicatif et votre numéro de mobile.', choose: 'Choisissez au moins une langue pour continuer.', invalidCode: 'Code incorrect ou expiré. Veuillez réessayer.', photo: 'Deux personnes discutent dehors avec des écouteurs', signIn: 'Se connecter et commencer', loading: 'Chargement d’Ekam…',
  },
  gu: {
    heading: 'કોઈની પણ સાથે {તેમની>તમારી}|માતૃભાષામાં વાત કરો', mobile: 'મોબાઇલ નંબર', country: 'દેશ / પ્રદેશ', name: 'તમારું નામ', firstName: 'તમારું નામ', languages: 'તમારી ભાષા', select: 'એક ભાષા પસંદ કરો.', code: 'ચકાસણી કોડ', test: 'ટેસ્ટ મોડ: કોઈ SMS મોકલ્યો નથી.', testCode: 'ટેસ્ટ કોડ:', privacy: 'અમે તમારો ફોન નંબર સામેની વ્યક્તિ સાથે ક્યારેય શેર કરીશું નહીં.', send: 'ચકાસણી કોડ મોકલો', verify: 'ચકાસો અને આગળ વધો', finish: 'વાતચીત શરૂ કરો', error: 'કંઈક ખોટું થયું. ફરી પ્રયાસ કરો.', indian: '10 અંકનો ભારતીય મોબાઇલ નંબર દાખલ કરો.', phoneError: 'તમારો દેશનો કોડ અને મોબાઇલ નંબર તપાસો.', choose: 'આગળ વધવા માટે ઓછામાં ઓછી એક ભાષા પસંદ કરો.', invalidCode: 'કોડ ખોટો છે અથવા તેની સમયમર્યાદા પૂરી થઈ ગઈ છે. ફરી પ્રયાસ કરો.', photo: 'ઇયરબડ્સ પહેરીને બહાર વાત કરતી બે વ્યક્તિઓ', signIn: 'સાઇન ઇન કરો અને શરૂ કરો', loading: 'Ekam લોડ થઈ રહ્યું છે…',
  },
  hi: {
    heading: 'किसी से भी {उनकी>अपनी}|मातृभाषा में बात करें', mobile: 'मोबाइल नंबर', country: 'देश / क्षेत्र', name: 'आपका नाम', firstName: 'आपका नाम', languages: 'आपकी भाषा', select: 'एक भाषा चुनें।', code: 'सत्यापन कोड', test: 'टेस्ट मोड: कोई SMS नहीं भेजा गया।', testCode: 'टेस्ट कोड:', privacy: 'हम आपका फ़ोन नंबर सामने वाले व्यक्ति के साथ कभी साझा नहीं करेंगे।', send: 'सत्यापन कोड भेजें', verify: 'सत्यापित करें और आगे बढ़ें', finish: 'बातचीत शुरू करें', error: 'कुछ गलत हो गया। फिर से कोशिश करें।', indian: '10 अंकों का भारतीय मोबाइल नंबर दर्ज करें।', phoneError: 'देश का कोड और मोबाइल नंबर जाँचें।', choose: 'आगे बढ़ने के लिए कम से कम एक भाषा चुनें।', invalidCode: 'कोड गलत है या उसकी समय-सीमा समाप्त हो गई है। फिर से कोशिश करें।', photo: 'ईयरबड्स पहनकर बाहर बात करते दो लोग', signIn: 'साइन इन करें और शुरू करें', loading: 'Ekam लोड हो रहा है…',
  },
  kn: {
    heading: 'ಯಾರೊಂದಿಗಾದರೂ {ಅವರ>ನಿಮ್ಮ}|ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ', mobile: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ', country: 'ದೇಶ / ಪ್ರದೇಶ', name: 'ನಿಮ್ಮ ಹೆಸರು', firstName: 'ನಿಮ್ಮ ಹೆಸರು', languages: 'ನಿಮ್ಮ ಭಾಷೆ', select: 'ಒಂದು ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.', code: 'ಪರಿಶೀಲನಾ ಕೋಡ್', test: 'ಪರೀಕ್ಷಾ ಮೋಡ್: SMS ಕಳುಹಿಸಲಾಗಿಲ್ಲ.', testCode: 'ಪರೀಕ್ಷಾ ಕೋಡ್:', privacy: 'ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನೀವು ಮಾತನಾಡುತ್ತಿರುವ ವ್ಯಕ್ತಿಯೊಂದಿಗೆ ನಾವು ಎಂದಿಗೂ ಹಂಚಿಕೊಳ್ಳುವುದಿಲ್ಲ.', send: 'ಪರಿಶೀಲನಾ ಕೋಡ್ ಕಳುಹಿಸಿ', verify: 'ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರಿಯಿರಿ', finish: 'ಮಾತನಾಡಲು ಪ್ರಾರಂಭಿಸೋಣ', error: 'ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.', indian: '10 ಅಂಕಿಗಳ ಭಾರತೀಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.', phoneError: 'ನಿಮ್ಮ ದೇಶದ ಕೋಡ್ ಮತ್ತು ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ಪರಿಶೀಲಿಸಿ.', choose: 'ಮುಂದುವರಿಯಲು ಕನಿಷ್ಠ ಒಂದು ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.', invalidCode: 'ಕೋಡ್ ತಪ್ಪಾಗಿದೆ ಅಥವಾ ಅವಧಿ ಮುಗಿದಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.', photo: 'ಇಯರ್‌ಬಡ್ಸ್ ಧರಿಸಿ ಹೊರಗೆ ಮಾತನಾಡುತ್ತಿರುವ ಇಬ್ಬರು', signIn: 'ಸೈನ್ ಇನ್ ಮಾಡಿ ಮತ್ತು ಪ್ರಾರಂಭಿಸಿ', loading: 'Ekam ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
  },
  bn: {"heading": "যে কারও সঙ্গে {তাদের>নিজের}|মাতৃভাষায় কথা বলুন", "mobile": "মোবাইল নম্বর", "country": "দেশ / অঞ্চল", "name": "আপনার নাম", "firstName": "আপনার নাম", "languages": "আপনার ভাষা", "select": "একটি ভাষা বেছে নিন।", "code": "যাচাইকরণ কোড", "test": "টেস্ট মোড: কোনো SMS পাঠানো হয়নি।", "testCode": "টেস্ট কোড:", "privacy": "আপনার ফোন নম্বর আপনার কথোপকথনের সঙ্গীর সঙ্গে কখনো শেয়ার করা হবে না।", "send": "যাচাইকরণ কোড পাঠান", "verify": "যাচাই করে এগিয়ে যান", "finish": "কথা শুরু করুন", "error": "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।", "indian": "১০ অঙ্কের ভারতীয় মোবাইল নম্বর লিখুন।", "phoneError": "দেশের কোড ও মোবাইল নম্বর পরীক্ষা করুন।", "choose": "এগিয়ে যেতে একটি ভাষা বেছে নিন।", "invalidCode": "কোড ভুল বা মেয়াদ শেষ। আবার চেষ্টা করুন।", "photo": "ইয়ারবাড পরে বাইরে কথা বলছেন দুজন", "signIn": "সাইন ইন করে শুরু করুন", "loading": "Ekam লোড হচ্ছে…"},
  ta: {"heading": "யாருடனும் {அவர்களின்>உங்கள்}|தாய்மொழியில் பேசுங்கள்", "mobile": "மொபைல் எண்", "country": "நாடு / பகுதி", "name": "உங்கள் பெயர்", "firstName": "உங்கள் பெயர்", "languages": "உங்கள் மொழி", "select": "ஒரு மொழியைத் தேர்ந்தெடுக்கவும்.", "code": "சரிபார்ப்புக் குறியீடு", "test": "சோதனை முறை: SMS அனுப்பப்படவில்லை.", "testCode": "சோதனைக் குறியீடு:", "privacy": "நீங்கள் பேசும் நபருடன் உங்கள் தொலைபேசி எண்ணை நாங்கள் ஒருபோதும் பகிரமாட்டோம்.", "send": "சரிபார்ப்புக் குறியீட்டை அனுப்பவும்", "verify": "சரிபார்த்து தொடரவும்", "finish": "பேசத் தொடங்குங்கள்", "error": "ஏதோ தவறு ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.", "indian": "10 இலக்க இந்திய மொபைல் எண்ணை உள்ளிடவும்.", "phoneError": "நாட்டுக் குறியீட்டையும் மொபைல் எண்ணையும் சரிபார்க்கவும்.", "choose": "தொடர ஒரு மொழியைத் தேர்ந்தெடுக்கவும்.", "invalidCode": "குறியீடு தவறானது அல்லது காலாவதியானது. மீண்டும் முயற்சிக்கவும்.", "photo": "இயர்பட்ஸ் அணிந்து வெளியில் பேசும் இருவர்", "signIn": "உள்நுழைந்து தொடங்குங்கள்", "loading": "Ekam ஏற்றப்படுகிறது…"},
  te: {"heading": "ఎవరితోనైనా {వారి>మీ}|మాతృభాషలో మాట్లాడండి", "mobile": "మొబైల్ నంబర్", "country": "దేశం / ప్రాంతం", "name": "మీ పేరు", "firstName": "మీ పేరు", "languages": "మీ భాష", "select": "ఒక భాషను ఎంచుకోండి.", "code": "ధృవీకరణ కోడ్", "test": "టెస్ట్ మోడ్: SMS పంపబడలేదు.", "testCode": "టెస్ట్ కోడ్:", "privacy": "మీరు మాట్లాడే వ్యక్తితో మీ ఫోన్ నంబర్‌ను మేము ఎప్పటికీ పంచుకోము.", "send": "ధృవీకరణ కోడ్ పంపండి", "verify": "ధృవీకరించి కొనసాగండి", "finish": "మాట్లాడటం ప్రారంభించండి", "error": "ఏదో తప్పు జరిగింది. మళ్లీ ప్రయత్నించండి.", "indian": "10 అంకెల భారతీయ మొబైల్ నంబర్‌ను నమోదు చేయండి.", "phoneError": "దేశం కోడ్ మరియు మొబైల్ నంబర్‌ను తనిఖీ చేయండి.", "choose": "కొనసాగడానికి ఒక భాషను ఎంచుకోండి.", "invalidCode": "కోడ్ తప్పు లేదా గడువు ముగిసింది. మళ్లీ ప్రయత్నించండి.", "photo": "ఇయర్‌బడ్స్ ధరించి బయట మాట్లాడుతున్న ఇద్దరు వ్యక్తులు", "signIn": "సైన్ ఇన్ చేసి ప్రారంభించండి", "loading": "Ekam లోడ్ అవుతోంది…"},
  ml: {"heading": "ആരോടും {അവരുടെ>നിങ്ങളുടെ}|മാതൃഭാഷയിൽ സംസാരിക്കൂ", "mobile": "മൊബൈൽ നമ്പർ", "country": "രാജ്യം / പ്രദേശം", "name": "നിങ്ങളുടെ പേര്", "firstName": "നിങ്ങളുടെ പേര്", "languages": "നിങ്ങളുടെ ഭാഷ", "select": "ഒരു ഭാഷ തിരഞ്ഞെടുക്കൂ.", "code": "സ്ഥിരീകരണ കോഡ്", "test": "ടെസ്റ്റ് മോഡ്: SMS അയച്ചിട്ടില്ല.", "testCode": "ടെസ്റ്റ് കോഡ്:", "privacy": "നിങ്ങൾ സംസാരിക്കുന്ന വ്യക്തിയുമായി നിങ്ങളുടെ ഫോൺ നമ്പർ ഞങ്ങൾ ഒരിക്കലും പങ്കിടില്ല.", "send": "സ്ഥിരീകരണ കോഡ് അയയ്ക്കുക", "verify": "സ്ഥിരീകരിച്ച് തുടരുക", "finish": "സംസാരിക്കാൻ തുടങ്ങൂ", "error": "എന്തോ പിശക് സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കൂ.", "indian": "10 അക്ക ഇന്ത്യൻ മൊബൈൽ നമ്പർ നൽകൂ.", "phoneError": "രാജ്യത്തിന്റെ കോഡും മൊബൈൽ നമ്പറും പരിശോധിക്കൂ.", "choose": "തുടരാൻ ഒരു ഭാഷ തിരഞ്ഞെടുക്കൂ.", "invalidCode": "കോഡ് തെറ്റാണ് അല്ലെങ്കിൽ കാലാവധി കഴിഞ്ഞു. വീണ്ടും ശ്രമിക്കൂ.", "photo": "ഇയർബഡ്സ് ധരിച്ച് പുറത്ത് സംസാരിക്കുന്ന രണ്ടുപേർ", "signIn": "സൈൻ ഇൻ ചെയ്ത് ആരംഭിക്കൂ", "loading": "Ekam ലോഡ് ചെയ്യുന്നു…"},
  mr: {"heading": "कोणाशीही {त्यांच्या>तुमच्या}|मातृभाषेत बोला", "mobile": "मोबाइल नंबर", "country": "देश / प्रदेश", "name": "तुमचे नाव", "firstName": "तुमचे नाव", "languages": "तुमची भाषा", "select": "एक भाषा निवडा.", "code": "पडताळणी कोड", "test": "चाचणी मोड: SMS पाठवलेला नाही.", "testCode": "चाचणी कोड:", "privacy": "तुम्ही ज्या व्यक्तीशी बोलत आहात तिच्यासोबत आम्ही तुमचा फोन नंबर कधीही शेअर करणार नाही.", "send": "पडताळणी कोड पाठवा", "verify": "पडताळा आणि पुढे जा", "finish": "बोलायला सुरुवात करा", "error": "काहीतरी चूक झाली. पुन्हा प्रयत्न करा.", "indian": "१० अंकी भारतीय मोबाइल नंबर टाका.", "phoneError": "देशाचा कोड आणि मोबाइल नंबर तपासा.", "choose": "पुढे जाण्यासाठी एक भाषा निवडा.", "invalidCode": "कोड चुकीचा आहे किंवा त्याची मुदत संपली आहे. पुन्हा प्रयत्न करा.", "photo": "इअरबड्स घालून बाहेर बोलत असलेल्या दोन व्यक्ती", "signIn": "साइन इन करून सुरुवात करा", "loading": "Ekam लोड होत आहे…"},
  pa: {"heading": "ਕਿਸੇ ਨਾਲ ਵੀ {ਉਨ੍ਹਾਂ ਦੀ>ਆਪਣੀ}|ਮਾਂ-ਬੋਲੀ ਵਿੱਚ ਗੱਲ ਕਰੋ", "mobile": "ਮੋਬਾਈਲ ਨੰਬਰ", "country": "ਦੇਸ਼ / ਖੇਤਰ", "name": "ਤੁਹਾਡਾ ਨਾਮ", "firstName": "ਤੁਹਾਡਾ ਨਾਮ", "languages": "ਤੁਹਾਡੀ ਭਾਸ਼ਾ", "select": "ਇੱਕ ਭਾਸ਼ਾ ਚੁਣੋ।", "code": "ਪੁਸ਼ਟੀਕਰਨ ਕੋਡ", "test": "ਟੈਸਟ ਮੋਡ: ਕੋਈ SMS ਨਹੀਂ ਭੇਜਿਆ ਗਿਆ।", "testCode": "ਟੈਸਟ ਕੋਡ:", "privacy": "ਅਸੀਂ ਤੁਹਾਡਾ ਫ਼ੋਨ ਨੰਬਰ ਉਸ ਵਿਅਕਤੀ ਨਾਲ ਕਦੇ ਸਾਂਝਾ ਨਹੀਂ ਕਰਾਂਗੇ ਜਿਸ ਨਾਲ ਤੁਸੀਂ ਗੱਲ ਕਰ ਰਹੇ ਹੋ।", "send": "ਪੁਸ਼ਟੀਕਰਨ ਕੋਡ ਭੇਜੋ", "verify": "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਅੱਗੇ ਵਧੋ", "finish": "ਗੱਲਬਾਤ ਸ਼ੁਰੂ ਕਰੋ", "error": "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।", "indian": "10 ਅੰਕਾਂ ਦਾ ਭਾਰਤੀ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।", "phoneError": "ਦੇਸ਼ ਦਾ ਕੋਡ ਅਤੇ ਮੋਬਾਈਲ ਨੰਬਰ ਜਾਂਚੋ।", "choose": "ਅੱਗੇ ਵਧਣ ਲਈ ਇੱਕ ਭਾਸ਼ਾ ਚੁਣੋ।", "invalidCode": "ਕੋਡ ਗਲਤ ਹੈ ਜਾਂ ਮਿਆਦ ਪੁੱਗ ਗਈ ਹੈ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।", "photo": "ਈਅਰਬਡਸ ਪਹਿਨ ਕੇ ਬਾਹਰ ਗੱਲ ਕਰਦੇ ਦੋ ਲੋਕ", "signIn": "ਸਾਈਨ ਇਨ ਕਰੋ ਅਤੇ ਸ਼ੁਰੂ ਕਰੋ", "loading": "Ekam ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…"},
};
